name: CI Pipeline for Agile Final Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install html5validator
        run: |
          pip install html5validator
          html5validator --version  # This will show the installed version
          which html5validator      # Confirm html5validator location

      - name: List directory contents
        run: ls -R # This will list all files and folders in the repository

      - name: Run html5validator on HTML files
        run: |
          # Validate all HTML files with the correct root directory
          html5validator --root ./  --also-check-css --also-check-svg || echo "HTML Validation failed"
