name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validate HTML files
        uses: wagoid/commitlint-github-action@v3
        with:
          configFile: ".github/commitlint-config"

      - name: Validate CSS files
        run: |
          npm install -g stylelint
          stylelint "**/*.css"

      - name: Validate JS files
        run: |
          npm install -g eslint
          eslint "**/*.js"

      - name: Validate JSON files
        run: |
          npm install -g jsonlint
          jsonlint "**/*.json"
