name: CI Pipeline for Agile Final Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run basic checks
        run: |
          echo "Running basic HTML/CSS/JS check"
          echo "All files present:"
          ls -al

      - name: Validate HTML
        uses: Cyb3r-Jak3/html5validator-action@v0.4.1
        with:
          root: .

      - name: Success Message
        run: echo "CI check completed successfully"
